language: c

notifications:
  - email: true

before_install:
  # Install the arm32 cross-compiler
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
  - arm-linux-gnueabihf-gcc --version
  # Install bc (required by the kernel)
  - sudo apt-get install bc
  # Install 32-bit compatibility libraries for the Linaro arm64 cross-compiler
  # (which is a 32-bit x86 binary)
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install libc6-i386 lib32stdc++6 lib32z1; fi

before_script:
  # Store the home repository
  - export MYHOME=$PWD

script:
  # Check coding style
  - git format-patch -1 --stdout | $DST_KERNEL/scripts/checkpatch.pl --ignore FILE_PATH_CHANGES --ignore GERRIT_CHANGE_ID -

  # arm32 compilation
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  - echo "CONFIG_IPIPE=y" >> arch/arm/configs/sunxi_defconfig
  - make sunxi_defconfig
  - make -j`getconf _NPROCESSORS_ONLN` zImage
  
  # arm64 compilation
  - export ARCH=arm64
  - export CROSS_COMPILE=aarch64-linux-gnu-
  - rm -f .config
  - make defconfig
  - make -j`getconf _NPROCESSORS_ONLN` all
